//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MDT_MonitorModel", "ComputerHasIdentities", "Computers", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(UCLMDTCustomizations.Models.Computer), "ComputerIdentity", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(UCLMDTCustomizations.Models.ComputerIdentity), true)]
[assembly: EdmRelationshipAttribute("MDT_MonitorModel", "ComputerLog", "Computer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(UCLMDTCustomizations.Models.Computer), "Log", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(UCLMDTCustomizations.Models.Log), true)]
[assembly: EdmRelationshipAttribute("MDT_MonitorModel", "ComputerProperty", "Computer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(UCLMDTCustomizations.Models.Computer), "Property", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(UCLMDTCustomizations.Models.Property), true)]

#endregion

namespace UCLMDTCustomizations.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ComputerIdentity> ComputerIdentities
        {
            get
            {
                if ((_ComputerIdentities == null))
                {
                    _ComputerIdentities = base.CreateObjectSet<ComputerIdentity>("ComputerIdentities");
                }
                return _ComputerIdentities;
            }
        }
        private ObjectSet<ComputerIdentity> _ComputerIdentities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Computer> Computers
        {
            get
            {
                if ((_Computers == null))
                {
                    _Computers = base.CreateObjectSet<Computer>("Computers");
                }
                return _Computers;
            }
        }
        private ObjectSet<Computer> _Computers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NextID> NextIDs
        {
            get
            {
                if ((_NextIDs == null))
                {
                    _NextIDs = base.CreateObjectSet<NextID>("NextIDs");
                }
                return _NextIDs;
            }
        }
        private ObjectSet<NextID> _NextIDs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Log> Logs
        {
            get
            {
                if ((_Logs == null))
                {
                    _Logs = base.CreateObjectSet<Log>("Logs");
                }
                return _Logs;
            }
        }
        private ObjectSet<Log> _Logs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Property> Properties
        {
            get
            {
                if ((_Properties == null))
                {
                    _Properties = base.CreateObjectSet<Property>("Properties");
                }
                return _Properties;
            }
        }
        private ObjectSet<Property> _Properties;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ComputerIdentities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComputerIdentities(ComputerIdentity computerIdentity)
        {
            base.AddObject("ComputerIdentities", computerIdentity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Computers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComputers(Computer computer)
        {
            base.AddObject("Computers", computer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NextIDs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNextIDs(NextID nextID)
        {
            base.AddObject("NextIDs", nextID);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Logs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLogs(Log log)
        {
            base.AddObject("Logs", log);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Properties EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProperties(Property property)
        {
            base.AddObject("Properties", property);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MDT_MonitorModel", Name="Computer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Computer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Computer object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="uniqueID">Initial value of the UniqueID property.</param>
        public static Computer CreateComputer(global::System.Int32 id, global::System.Guid uniqueID)
        {
            Computer computer = new Computer();
            computer.ID = id;
            computer.UniqueID = uniqueID;
            return computer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> PercentComplete
        {
            get
            {
                return _PercentComplete;
            }
            set
            {
                OnPercentCompleteChanging(value);
                ReportPropertyChanging("PercentComplete");
                _PercentComplete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PercentComplete");
                OnPercentCompleteChanged();
            }
        }
        private Nullable<global::System.Int16> _PercentComplete;
        partial void OnPercentCompleteChanging(Nullable<global::System.Int16> value);
        partial void OnPercentCompleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Settings
        {
            get
            {
                return _Settings;
            }
            set
            {
                OnSettingsChanging(value);
                ReportPropertyChanging("Settings");
                _Settings = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Settings");
                OnSettingsChanged();
            }
        }
        private global::System.String _Settings;
        partial void OnSettingsChanging(global::System.String value);
        partial void OnSettingsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Warnings
        {
            get
            {
                return _Warnings;
            }
            set
            {
                OnWarningsChanging(value);
                ReportPropertyChanging("Warnings");
                _Warnings = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Warnings");
                OnWarningsChanged();
            }
        }
        private Nullable<global::System.Int32> _Warnings;
        partial void OnWarningsChanging(Nullable<global::System.Int32> value);
        partial void OnWarningsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Errors
        {
            get
            {
                return _Errors;
            }
            set
            {
                OnErrorsChanging(value);
                ReportPropertyChanging("Errors");
                _Errors = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Errors");
                OnErrorsChanged();
            }
        }
        private Nullable<global::System.Int32> _Errors;
        partial void OnErrorsChanging(Nullable<global::System.Int32> value);
        partial void OnErrorsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DeploymentStatus
        {
            get
            {
                return _DeploymentStatus;
            }
            set
            {
                OnDeploymentStatusChanging(value);
                ReportPropertyChanging("DeploymentStatus");
                _DeploymentStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeploymentStatus");
                OnDeploymentStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _DeploymentStatus;
        partial void OnDeploymentStatusChanging(Nullable<global::System.Int32> value);
        partial void OnDeploymentStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartTime;
        partial void OnStartTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndTime;
        partial void OnEndTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UniqueID
        {
            get
            {
                return _UniqueID;
            }
            set
            {
                OnUniqueIDChanging(value);
                ReportPropertyChanging("UniqueID");
                _UniqueID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UniqueID");
                OnUniqueIDChanged();
            }
        }
        private global::System.Guid _UniqueID;
        partial void OnUniqueIDChanging(global::System.Guid value);
        partial void OnUniqueIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CurrentStep
        {
            get
            {
                return _CurrentStep;
            }
            set
            {
                OnCurrentStepChanging(value);
                ReportPropertyChanging("CurrentStep");
                _CurrentStep = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrentStep");
                OnCurrentStepChanged();
            }
        }
        private Nullable<global::System.Int32> _CurrentStep;
        partial void OnCurrentStepChanging(Nullable<global::System.Int32> value);
        partial void OnCurrentStepChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TotalSteps
        {
            get
            {
                return _TotalSteps;
            }
            set
            {
                OnTotalStepsChanging(value);
                ReportPropertyChanging("TotalSteps");
                _TotalSteps = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalSteps");
                OnTotalStepsChanged();
            }
        }
        private Nullable<global::System.Int32> _TotalSteps;
        partial void OnTotalStepsChanging(Nullable<global::System.Int32> value);
        partial void OnTotalStepsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StepName
        {
            get
            {
                return _StepName;
            }
            set
            {
                OnStepNameChanging(value);
                ReportPropertyChanging("StepName");
                _StepName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StepName");
                OnStepNameChanged();
            }
        }
        private global::System.String _StepName;
        partial void OnStepNameChanging(global::System.String value);
        partial void OnStepNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastTime
        {
            get
            {
                return _LastTime;
            }
            set
            {
                OnLastTimeChanging(value);
                ReportPropertyChanging("LastTime");
                _LastTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastTime");
                OnLastTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastTime;
        partial void OnLastTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLastTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DartIP
        {
            get
            {
                return _DartIP;
            }
            set
            {
                OnDartIPChanging(value);
                ReportPropertyChanging("DartIP");
                _DartIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DartIP");
                OnDartIPChanged();
            }
        }
        private global::System.String _DartIP;
        partial void OnDartIPChanging(global::System.String value);
        partial void OnDartIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DartPort
        {
            get
            {
                return _DartPort;
            }
            set
            {
                OnDartPortChanging(value);
                ReportPropertyChanging("DartPort");
                _DartPort = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DartPort");
                OnDartPortChanged();
            }
        }
        private global::System.String _DartPort;
        partial void OnDartPortChanging(global::System.String value);
        partial void OnDartPortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DartTicket
        {
            get
            {
                return _DartTicket;
            }
            set
            {
                OnDartTicketChanging(value);
                ReportPropertyChanging("DartTicket");
                _DartTicket = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DartTicket");
                OnDartTicketChanged();
            }
        }
        private global::System.String _DartTicket;
        partial void OnDartTicketChanging(global::System.String value);
        partial void OnDartTicketChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VMHost
        {
            get
            {
                return _VMHost;
            }
            set
            {
                OnVMHostChanging(value);
                ReportPropertyChanging("VMHost");
                _VMHost = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VMHost");
                OnVMHostChanged();
            }
        }
        private global::System.String _VMHost;
        partial void OnVMHostChanging(global::System.String value);
        partial void OnVMHostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VMName
        {
            get
            {
                return _VMName;
            }
            set
            {
                OnVMNameChanging(value);
                ReportPropertyChanging("VMName");
                _VMName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VMName");
                OnVMNameChanged();
            }
        }
        private global::System.String _VMName;
        partial void OnVMNameChanging(global::System.String value);
        partial void OnVMNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TestColumn
        {
            get
            {
                return _TestColumn;
            }
            set
            {
                OnTestColumnChanging(value);
                ReportPropertyChanging("TestColumn");
                _TestColumn = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TestColumn");
                OnTestColumnChanged();
            }
        }
        private global::System.String _TestColumn;
        partial void OnTestColumnChanging(global::System.String value);
        partial void OnTestColumnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Severity
        {
            get
            {
                return _Severity;
            }
            set
            {
                OnSeverityChanging(value);
                ReportPropertyChanging("Severity");
                _Severity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Severity");
                OnSeverityChanged();
            }
        }
        private global::System.String _Severity;
        partial void OnSeverityChanging(global::System.String value);
        partial void OnSeverityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MessageID
        {
            get
            {
                return _MessageID;
            }
            set
            {
                OnMessageIDChanging(value);
                ReportPropertyChanging("MessageID");
                _MessageID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MessageID");
                OnMessageIDChanged();
            }
        }
        private global::System.String _MessageID;
        partial void OnMessageIDChanging(global::System.String value);
        partial void OnMessageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Custodian
        {
            get
            {
                return _Custodian;
            }
            set
            {
                OnCustodianChanging(value);
                ReportPropertyChanging("Custodian");
                _Custodian = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Custodian");
                OnCustodianChanged();
            }
        }
        private global::System.String _Custodian;
        partial void OnCustodianChanging(global::System.String value);
        partial void OnCustodianChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Room
        {
            get
            {
                return _Room;
            }
            set
            {
                OnRoomChanging(value);
                ReportPropertyChanging("Room");
                _Room = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Room");
                OnRoomChanged();
            }
        }
        private global::System.String _Room;
        partial void OnRoomChanging(global::System.String value);
        partial void OnRoomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ComputerName
        {
            get
            {
                return _ComputerName;
            }
            set
            {
                OnComputerNameChanging(value);
                ReportPropertyChanging("ComputerName");
                _ComputerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ComputerName");
                OnComputerNameChanged();
            }
        }
        private global::System.String _ComputerName;
        partial void OnComputerNameChanging(global::System.String value);
        partial void OnComputerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> UUID
        {
            get
            {
                return _UUID;
            }
            set
            {
                OnUUIDChanging(value);
                ReportPropertyChanging("UUID");
                _UUID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UUID");
                OnUUIDChanged();
            }
        }
        private Nullable<global::System.Guid> _UUID;
        partial void OnUUIDChanging(Nullable<global::System.Guid> value);
        partial void OnUUIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MacAddresses
        {
            get
            {
                return _MacAddresses;
            }
            set
            {
                OnMacAddressesChanging(value);
                ReportPropertyChanging("MacAddresses");
                _MacAddresses = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MacAddresses");
                OnMacAddressesChanged();
            }
        }
        private global::System.String _MacAddresses;
        partial void OnMacAddressesChanging(global::System.String value);
        partial void OnMacAddressesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Operator
        {
            get
            {
                return _Operator;
            }
            set
            {
                OnOperatorChanging(value);
                ReportPropertyChanging("Operator");
                _Operator = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Operator");
                OnOperatorChanged();
            }
        }
        private global::System.String _Operator;
        partial void OnOperatorChanging(global::System.String value);
        partial void OnOperatorChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MDT_MonitorModel", "ComputerHasIdentities", "ComputerIdentity")]
        public EntityCollection<ComputerIdentity> ComputerIdentities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ComputerIdentity>("MDT_MonitorModel.ComputerHasIdentities", "ComputerIdentity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ComputerIdentity>("MDT_MonitorModel.ComputerHasIdentities", "ComputerIdentity", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MDT_MonitorModel", "ComputerLog", "Log")]
        public EntityCollection<Log> Logs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Log>("MDT_MonitorModel.ComputerLog", "Log");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Log>("MDT_MonitorModel.ComputerLog", "Log", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MDT_MonitorModel", "ComputerProperty", "Property")]
        public EntityCollection<Property> Properties
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Property>("MDT_MonitorModel.ComputerProperty", "Property");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Property>("MDT_MonitorModel.ComputerProperty", "Property", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MDT_MonitorModel", Name="ComputerIdentity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ComputerIdentity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ComputerIdentity object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="identifier">Initial value of the Identifier property.</param>
        public static ComputerIdentity CreateComputerIdentity(global::System.Int32 id, global::System.String identifier)
        {
            ComputerIdentity computerIdentity = new ComputerIdentity();
            computerIdentity.ID = id;
            computerIdentity.Identifier = identifier;
            return computerIdentity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Identifier
        {
            get
            {
                return _Identifier;
            }
            set
            {
                if (_Identifier != value)
                {
                    OnIdentifierChanging(value);
                    ReportPropertyChanging("Identifier");
                    _Identifier = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Identifier");
                    OnIdentifierChanged();
                }
            }
        }
        private global::System.String _Identifier;
        partial void OnIdentifierChanging(global::System.String value);
        partial void OnIdentifierChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MDT_MonitorModel", "ComputerHasIdentities", "Computers")]
        public Computer Computer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Computer>("MDT_MonitorModel.ComputerHasIdentities", "Computers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Computer>("MDT_MonitorModel.ComputerHasIdentities", "Computers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Computer> ComputerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Computer>("MDT_MonitorModel.ComputerHasIdentities", "Computers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Computer>("MDT_MonitorModel.ComputerHasIdentities", "Computers", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MDT_MonitorModel", Name="Log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Log : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Log object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="file">Initial value of the File property.</param>
        /// <param name="fileName">Initial value of the FileName property.</param>
        /// <param name="computerID">Initial value of the ComputerID property.</param>
        public static Log CreateLog(global::System.Int32 id, global::System.String file, global::System.String fileName, global::System.Int32 computerID)
        {
            Log log = new Log();
            log.Id = id;
            log.File = file;
            log.FileName = fileName;
            log.ComputerID = computerID;
            return log;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String File
        {
            get
            {
                return _File;
            }
            set
            {
                OnFileChanging(value);
                ReportPropertyChanging("File");
                _File = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("File");
                OnFileChanged();
            }
        }
        private global::System.String _File;
        partial void OnFileChanging(global::System.String value);
        partial void OnFileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ComputerID
        {
            get
            {
                return _ComputerID;
            }
            set
            {
                OnComputerIDChanging(value);
                ReportPropertyChanging("ComputerID");
                _ComputerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ComputerID");
                OnComputerIDChanged();
            }
        }
        private global::System.Int32 _ComputerID;
        partial void OnComputerIDChanging(global::System.Int32 value);
        partial void OnComputerIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MDT_MonitorModel", "ComputerLog", "Computer")]
        public Computer Computer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Computer>("MDT_MonitorModel.ComputerLog", "Computer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Computer>("MDT_MonitorModel.ComputerLog", "Computer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Computer> ComputerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Computer>("MDT_MonitorModel.ComputerLog", "Computer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Computer>("MDT_MonitorModel.ComputerLog", "Computer", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MDT_MonitorModel", Name="NextID")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NextID : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NextID object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static NextID CreateNextID(global::System.Int32 id)
        {
            NextID nextID = new NextID();
            nextID.ID = id;
            return nextID;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NextValue
        {
            get
            {
                return _NextValue;
            }
            set
            {
                OnNextValueChanging(value);
                ReportPropertyChanging("NextValue");
                _NextValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NextValue");
                OnNextValueChanged();
            }
        }
        private Nullable<global::System.Int32> _NextValue;
        partial void OnNextValueChanging(Nullable<global::System.Int32> value);
        partial void OnNextValueChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MDT_MonitorModel", Name="Property")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Property : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Property object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="computerID">Initial value of the ComputerID property.</param>
        public static Property CreateProperty(global::System.Int32 id, global::System.Int32 computerID)
        {
            Property property = new Property();
            property.Id = id;
            property.ComputerID = computerID;
            return property;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PropertyKey
        {
            get
            {
                return _PropertyKey;
            }
            set
            {
                OnPropertyKeyChanging(value);
                ReportPropertyChanging("PropertyKey");
                _PropertyKey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PropertyKey");
                OnPropertyKeyChanged();
            }
        }
        private global::System.String _PropertyKey;
        partial void OnPropertyKeyChanging(global::System.String value);
        partial void OnPropertyKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PropertyValue
        {
            get
            {
                return _PropertyValue;
            }
            set
            {
                OnPropertyValueChanging(value);
                ReportPropertyChanging("PropertyValue");
                _PropertyValue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PropertyValue");
                OnPropertyValueChanged();
            }
        }
        private global::System.String _PropertyValue;
        partial void OnPropertyValueChanging(global::System.String value);
        partial void OnPropertyValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ComputerID
        {
            get
            {
                return _ComputerID;
            }
            set
            {
                OnComputerIDChanging(value);
                ReportPropertyChanging("ComputerID");
                _ComputerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ComputerID");
                OnComputerIDChanged();
            }
        }
        private global::System.Int32 _ComputerID;
        partial void OnComputerIDChanging(global::System.Int32 value);
        partial void OnComputerIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MDT_MonitorModel", "ComputerProperty", "Computer")]
        public Computer Computer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Computer>("MDT_MonitorModel.ComputerProperty", "Computer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Computer>("MDT_MonitorModel.ComputerProperty", "Computer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Computer> ComputerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Computer>("MDT_MonitorModel.ComputerProperty", "Computer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Computer>("MDT_MonitorModel.ComputerProperty", "Computer", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
